import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './component/Header';
import Navbar from './component/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='relative w-full'>
          <Header />
          <Navbar />
          <div className='absolute top-20 left-[20%] bg-slate-100 p-5 w-[80%]'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
