export const product_mock = [
  {
    product_id: 108,
    listed_price: 2000000,
    price: 15000000,
    name: 'bàn ghế fake mock data fake ',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      '        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: '',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 109,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      '        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: '',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 110,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      '        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: '',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 111,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      '        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: '',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 112,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      '        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: '',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 113,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: '',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 114,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
    image: '',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 115,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
    image: '',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 116,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
    image: '',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 117,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
    image: '',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 118,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: '',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 119,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: 'r',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 120,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: 'r',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 121,
    listed_price: 2005660000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: 'r',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 122,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: 'r',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 124,
    listed_price: 2000000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: 'r',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
  {
    product_id: 125,
    listed_price: 20000,
    price: 1500000,
    name: 'bàn ghế fake mock data fake',
    dimensions: 'S:55x55x180cm M:60x50x190cm L:65x55x200cm',
    available: 'Cần đặt trước 10 ngày',
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.\r\n',
    image: 'r',
    status: true,
    material_id: 100,
    type_id: 100,
    category_id: 100,
    category: {
      category_id: 100,
      name: 'bàn ghế fake mock data fake',
      description:
        'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae suscipit nulla ut eos quasi! Nostrum, ipsam? Voluptatum nihil expedita eos, eligendi dolorem aliquid nesciunt harum alias porro praesentium, tenetur incidunt.',
      image: 'cc',
    },
    productType: {
      type_id: 100,
      name: 'New',
      description: 'tét',
      image: '',
    },
    material: {
      material_id: 100,
      name: 'Hương đá',
      description: 'tét',
      image: '',
    },
  },
];
